name: Test python package

on:
  push:
    paths:
    - src/**
    - .github/workflows/test.yml
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10','3.11','3.12','3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: python -m pip install -U pip

      - name: Install package
        run: python -m pip install -e .

      - name: Run startup test
        run: |
          damast-ais-showcase 2> output.log &
          sleep 5
          grep "Dash is running on" output.log

